"""
A2A Server for Green Agent (CIO-Agent FAB++ Evaluator)

This is the main entry point for the Green Agent A2A server.
It exposes the FAB++ evaluation capabilities via the A2A protocol,
allowing the AgentBeats platform to run assessments.

Usage:
    uv run src/cio_agent/a2a_server.py --host 0.0.0.0 --port 9009
    
    # With synthetic questions:
    uv run src/cio_agent/a2a_server.py --host 0.0.0.0 --port 9009 \\
        --synthetic-questions data/synthetic_questions/questions.json
    
    # Or with Docker:
    docker run -p 9009:9009 ghcr.io/your-org/cio-agent-green:latest --host 0.0.0.0

The server accepts:
    --host: Host address to bind to (default: 127.0.0.1)
    --port: Port to listen on (default: 9009)
    --card-url: URL to advertise in the agent card (optional)
    --synthetic-questions: Path to synthetic questions JSON file (optional)
"""

import argparse
import json
import os
from pathlib import Path
import uvicorn
from sqlalchemy.ext.asyncio import create_async_engine

from dotenv import load_dotenv
from a2a.server.apps import A2AStarletteApplication
from a2a.server.request_handlers import DefaultRequestHandler
from a2a.server.tasks import DatabaseTaskStore
from a2a.types import (
    AgentCapabilities,
    AgentCard,
    AgentSkill,
)

from cio_agent.green_executor import GreenAgentExecutor

# Load environment variables from .env file
load_dotenv()


def load_synthetic_questions(file_path: str) -> list[dict]:
    """Load synthetic questions from a JSON file."""
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"Synthetic questions file not found: {file_path}")
    
    data = json.loads(path.read_text())
    questions = data.get("questions", [])
    if not questions:
        raise ValueError(f"No questions found in {file_path}")
    
    print(f"Loaded {len(questions)} synthetic questions from {file_path}")
    return questions


def main():
    """Main entry point for the Green Agent A2A server."""
    parser = argparse.ArgumentParser(description="Run the CIO-Agent Green Agent A2A server.")
    parser.add_argument(
        "--host",
        type=str,
        default="127.0.0.1",
        help="Host to bind the server"
    )
    parser.add_argument(
        "--port",
        type=int,
        default=9009,
        help="Port to bind the server"
    )
    parser.add_argument(
        "--card-url",
        type=str,
        help="URL to advertise in the agent card"
    )
    parser.add_argument(
        "--synthetic-questions",
        type=str,
        help="Path to synthetic questions JSON file (generated by 'cio-agent generate-synthetic')"
    )
    args = parser.parse_args()

    # Load synthetic questions if provided
    synthetic_questions = None
    if args.synthetic_questions:
        try:
            synthetic_questions = load_synthetic_questions(args.synthetic_questions)
        except (FileNotFoundError, ValueError) as e:
            print(f"Error loading synthetic questions: {e}")
            return 1

    # Define agent skills
    skill = AgentSkill(
        id="fab-plus-plus-evaluation",
        name="FAB++ Finance Agent Benchmark",
        description=(
            "Evaluates finance agents using the FAB++ (Finance Agent Benchmark Plus Plus) "
            "framework. Assesses agents on macro analysis, fundamental accuracy, execution "
            "quality, and adversarial robustness. Provides comprehensive Alpha Scores."
        ),
        tags=[
            "finance",
            "evaluation",
            "benchmark",
            "agent-assessment",
            "adversarial-debate",
        ],
        examples=[
            "Evaluate a finance agent's ability to analyze NVIDIA Q3 earnings",
            "Test agent robustness with adversarial counter-arguments",
            "Assess fundamental data accuracy and macro thesis quality",
        ]
    )

    # Determine the advertised URL
    # Note: 0.0.0.0 is a bind address, not connectable. Use 127.0.0.1 for local testing.
    advertised_host = "127.0.0.1" if args.host == "0.0.0.0" else args.host
    card_url = args.card_url or f"http://{advertised_host}:{args.port}/"

    # Create agent card
    agent_card = AgentCard(
        name="CIO-Agent FAB++ Evaluator",
        description=(
            "A Green Agent for the AgentBeats platform that evaluates finance agents "
            "using the FAB++ (Finance Agent Benchmark Plus Plus) methodology. "
            "Tests agents on earnings analysis, SEC filing interpretation, numerical "
            "reasoning, and investment recommendations with adversarial robustness testing."
        ),
        url=card_url,
        version='1.0.0',
        default_input_modes=['text'],
        default_output_modes=['text'],
        capabilities=AgentCapabilities(streaming=True),
        skills=[skill]
    )

    # Create request handler with executor
    database_url = os.getenv("DATABASE_URL", "sqlite+aiosqlite:///tasks.db")
    print(f"Using database task store: {database_url}")
    engine = create_async_engine(database_url)
    task_store = DatabaseTaskStore(engine)
    
    request_handler = DefaultRequestHandler(
        agent_executor=GreenAgentExecutor(synthetic_questions=synthetic_questions),
        task_store=task_store,
    )
    
    # Create A2A application
    server = A2AStarletteApplication(
        agent_card=agent_card,
        http_handler=request_handler,
    )
    
    print(f"Starting CIO-Agent Green Agent A2A server...")
    print(f"  Host: {args.host}")
    print(f"  Port: {args.port}")
    print(f"  Agent Card URL: {agent_card.url}")
    print(f"  Agent Card: http://{args.host}:{args.port}/.well-known/agent.json")
    if synthetic_questions:
        print(f"  Synthetic Questions: {len(synthetic_questions)} loaded")
    
    uvicorn.run(server.build(), host=args.host, port=args.port)


if __name__ == '__main__':
    main()
